POST http://localhost:3000/session HTTP/1.1
content-type: application/json

{
    "username": "ciaoneeeeee"
}

###

PUT http://localhost:3000/profiles/6/username HTTP/1.1
Authorization: 6
content-type: application/json

{
    "username": "mariokkkk"
}

###

PUT http://localhost:3000/profiles/6/followings/8 HTTP/1.1
Authorization: 6

###

DELETE http://localhost:3000/profiles/6/followings/8 HTTP/1.1
Authorization: 6

###