
# DO LOGIN #
POST http://localhost:3000/session HTTP/1.1
content-type: application/json

{
    "username": "lokki"
}

###

# CHANGE USERNAME #
PUT http://localhost:3000/profiles/3/username HTTP/1.1
Authorization: 3
content-type: application/json

{
    "username": "cre"
}

###

# FOLLOW #
PUT http://localhost:3000/profiles/15/followings/5 HTTP/1.1
Authorization: 15

###

# UNFOLLOW #
DELETE http://localhost:3000/profiles/15/followings/5 HTTP/1.1
Authorization: 15

###

# BAN #
POST http://localhost:3000/profiles/3/bans HTTP/1.1
Authorization: 1

###

# UNBAN #
DELETE http://localhost:3000/profiles/36/bans/10 HTTP/1.1
Authorization: 36

###

# GET BANS #
GET http://localhost:3000/profiles/1/bans HTTP/1.1
Authorization: 1

###

# GET POSTS #
GET http://localhost:3000/profiles/3/posts HTTP/1.1
Authorization: 3

###

# UPLOAD POSTS #
POST http://localhost:3000/profiles/1/posts HTTP/1.1
Authorization: 1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="caption"

ciao
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="image.jpeg"
Content-Type: image/jpeg

------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

# LIKE #
POST http://localhost:3000/profiles/16/posts/8/likes HTTP/1.1
Authorization: 14

###

# UNLIKE #
DELETE http://localhost:3000/profiles/16/posts/9/like HTTP/1.1
Authorization: 14

###

# GET LIKES #
GET http://localhost:3000/profiles/2/posts/1/likes HTTP/1.1
Authorization: 2

###

# COMMENT #
POST http://localhost:3000/profiles/5/posts/3/comments HTTP/1.1
Authorization: 1
content-type: application/json

{
    "text": "bella foto!"
}

###

# UNCOMMENT #
DELETE http://localhost:3000/profiles/2/posts/2/comments/4 HTTP/1.1
Authorization: 2

###

# GET COMMENTS #
GET http://localhost:3000/profiles/2/posts/2/comments
?limit=100
&offset=0
Authorization: 2

###

# GET PROFILE #
GET http://localhost:3000/profiles/5 HTTP/1.1
Authorization: 5

###

# GET FOLLOWINGS #
GET http://localhost:3000/profiles/5/followings HTTP/1.1
Authorization: 5

###

# GET FOLLOWERS #
GET http://localhost:3000/profiles/5/followers HTTP/1.1
Authorization: 5

###

# SET BIO #
PUT http://localhost:3000/profiles/100/bio HTTP/1.1
Authorization: 100
content-type: application/json

{
    "bio": "Sono un gatto bellissimo 🐱"
}

###

# GET FEED #
GET http://localhost:3000/profiles/11/feed HTTP/1.1
Authorization: 11

###

# GET SEARCH #
GET http://localhost:3000/profiles
    ?search=mi
    &offset=0
    &limit=10
Authorization: 1

###

# CHANGE CAPTION #
PUT http://localhost:3000/profiles/2/posts/10/caption HTTP/1.1
Authorization: 2
content-type: application/json

{
    "caption": "cia2222o"
}

###

# CHANGE PROPIC#
PUT http://localhost:3000/profiles/2/propic HTTP/1.1
Authorization: 2
Content-Type: image/png

